Clean up the repo, and convert it to python3.
Khan/graphie-to-png pull request #23
Opened 2024-05-08 00:13 UTC by csilvers

## Summary:
This repo has had a bit of bitrot.  It has submodules that seem to be
unused.  It's also very old code.  I kept the logic unchanged but
moved the code to python3.

Note that this must be deployed with parallel changes to the
Dockerfile in Khan/internal-services/graphie-to-png/.

Issue: https://khanacademy.atlassian.net/browse/INFRA-10116

## Test plan:
I ran:
```
% ./cleanup_svg.py < /usr/share/yelp-xsl/xslt/common/icons/yelp-note-advanced.svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M5.447 12.572A5.98 5.98 0 0 0 2 18v4h20v-4a5.98 5.98 0 0 0-3.441-5.424A8 8 0 0 1 12 16a8 8 0 0 1-6.553-3.428" class="yelp-svg-fill"/><path d="M12 3a5 5 0 0 0-5 5 5 5 0 0 0 5 5 5 5 0 0 0 5-5 5 5 0 0 0-5-5m0 3a2 2 0 0 1 2 2 2 2 0 0 1-2 2 2 2 0 0 1-2-2 2 2 0 0 1 2-2" class="yelp-svg-fill"/><path d="M15.312 6 19 7v2l-3.469 1zM14 11.312 13 15h-2l-1-3.469zM10 4.688 11 1h2l1 3.469zM8.688 10 5 9V7l3.469-1z" class="yelp-svg-fill"/><path d="m12.928 4.244 3.315-1.9 1.414 1.413-1.746 3.16zM15.757 8.928l1.9 3.315-1.414 1.414-3.16-1.746zM8.244 7.072l-1.9-3.315 1.413-1.414 3.16 1.746zM11.072 11.757l-3.315 1.9-1.414-1.414 1.746-3.16z" class="yelp-svg-fill"/></svg>
```
which seems plausible to me.

I also ran `cp secrets.py.example secrets.py; ./server.sh` and visited
http://localhost:8765/ and got a reasonable homepage.  I selected one
of the images from the dropdown and clicked "convert to image" and got
an error that the S3 key was wrong, which means the logic to talk to
S3 is looking good.

2024-05-08 15:08 UTC, benchristel approved these changes
Thanks for doing this! I left a couple questions inline, but LGTM.

I tested this locally with real credentials, and verified that I can create a Graphie image and paste the URL into an image widget in the content editor.

2024-05-08 15:08 UTC, benchristel commented on Makefile
> +npm_deps: package.json
What does the dependency on `package.json` do here? Since these are phony targets, I don't think `make` can use the dependencies to optimize things (e.g. skip installing NPM packages if the package.json has not changed)

2024-05-08 15:08 UTC, benchristel commented on cleanup_svg.py
> +                         cwd=_ROOT,
What's the advantage of changing the working directory here?

2024-05-08 15:15 UTC, benchristel requested changes
Hmm, I take it back, there seems to be something amiss when I paste the image link into the content editor:

```
There was an error loading the image URL: { "isTrusted": true }
```
<img width="394" alt="Screen Shot 2024-05-08 at 8 14 45 AM" src="https://github.com/Khan/graphie-to-png/assets/693920/63cb4433-0cb8-4a35-8abe-2b5c5f5cf002">

`isTrusted: true` is a red herring; it's a property on JavaScript `Error` objects. Apparently it's the only enumerable property; someone was trying to be too clever here:

```ts
this.setState({
    backgroundImageError: `There was an error loading the image URL: ${JSON.stringify(
        error,
        null,
        2,
    )}`,
});
```

Probably there's something wrong with the generated SVG URL, or maybe the SVG isn't getting uploaded to S3?

2024-05-08 15:42 UTC, mpolyak commented on requirements.txt
> +Werkzeug==3.0.3
How did you get this to work? I'm getting `ModuleNotFoundError: No module named 'werkzeug.contrib'`.

According to the internet `contrib` was removed in version 1. https://stackoverflow.com/questions/60624139/when-i-do-flask-run-it-shows-error-modulenotfounderror-no-module-named-werk

2024-05-08 16:30 UTC, csilvers commented on requirements.txt
> +Werkzeug==3.0.3
Interesting, I get the same error when running `./app.py` but not when running `./server.sh`.  I am guessing the latter does some weird way of importing that doesn't try to import that module?  In any case, the cache isn't used so I can just remove that code.

2024-05-08 17:06 UTC, mpolyak commented
> Probably there's something wrong with the generated SVG URL, or maybe the SVG isn't getting uploaded to S3?

I tested it running `./server.sh` and it does seem to work, however the URL it generates is indeed "invalid" for pasting back in, e.g.

```
web+graphie://ka-perseus-graphie.s3.amazonaws.com:443/191d901422d8d974e4534897848640a49943e799
```

The port, `:443` needs to be removed:
```
web+graphie://ka-perseus-graphie.s3.amazonaws.com/191d901422d8d974e4534897848640a49943e799
```

I don't know if this was the previous behaviour running locally, or a new regresion?

2024-05-08 21:39 UTC, csilvers commented
> web+graphie://ka-perseus-graphie.s3.amazonaws.com:443/191d901422d8d974e4534897848640a49943e799

OK, it took me a while but I can reproduce the problem.  I had a python2 gunicorn on my PATH which was throwing off my testing.  Let me get a fix.

2024-05-08 21:45 UTC, csilvers commented
OK, I pushed a fix.  It's hacky but I couldn't figure out a principled way to do it.  See what you think!

2024-05-09 13:58 UTC, mpolyak commented
> OK, I pushed a fix. It's hacky but I couldn't figure out a principled way to do it. See what you think!

The port is gone, but I noticed another issue, the "Convert to Image" generated URL has a `.svg` extension:

```
web+graphie://ka-perseus-graphie.s3.amazonaws.com/35b1f0d68ebb18fa6dcdc62ebd8a176fc4cdf2dd.svg
```

It shouldn't. The format URL format should be: `web+graphie://ka-perseus-graphie.s3.amazonaws.com/<hash>`

2024-05-09 15:56 UTC, csilvers commented
> The port is gone, but I noticed another issue, the "Convert to Image" generated URL has a .svg extension:

Hmm, I wonder why it worked with my testing.  That's concerning.  I think I know how the new issue came in, when I replaced the regexp with string operations.  I'll take a closer look and make sure I'm matching the old logic.

2024-05-15 21:15 UTC, csilvers commented
> > The port is gone, but I noticed another issue, the "Convert to Image" generated URL has a .svg extension:
>
> Hmm, I wonder why it worked with my testing. That's concerning. I think I know how the new issue came in, when I replaced the regexp with string operations. I'll take a closer look and make sure I'm matching the old logic.

OK, I am more carefully matching the old logic now.

2024-05-16 18:01 UTC, mpolyak approved these changes
Thanks! I pulled latest commit and the URL looks good as far as I can tell.

2024-05-17 16:08 UTC, benchristel requested changes
It looks like images are not being saved to S3. When I click the "convert to image" button, I see this error in the server STDOUT:

```
ERROR:root:Cleanup svg failed
Traceback (most recent call last):
  File "/Users/bchristel/khan/graphie-to-png/cleanup_svg.py", line 171, in cleanup_svg
    return _run_svgo(new_svgdata.decode('utf-8'))
  File "/Users/bchristel/khan/graphie-to-png/cleanup_svg.py", line 44, in _run_svgo
    encoding='utf-8')
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

2024-05-17 17:01 UTC, mpolyak commented
The Python2 docs do list `encoding` as one of the args that `subprocess.Popen` can take as far as I can tell: https://docs.python.org/2/library/subprocess.html#subprocess.Popen

But Python3 docs do: https://docs.python.org/3/library/subprocess.html#subprocess.Popen

For testing this PR I did something like:

```shell
cd khan/graphie-to-png/
git fetch
git pull
git co py3
virtualenv -p python3 graphie-to-png
source graphie-to-png/bin/activate
make deps
./server.sh
```

2024-05-17 17:18 UTC, merged

2024-05-17 17:21 UTC, csilvers commented
> It looks like images are not being saved to S3. When I click the "convert to image" button, I see this error in the server STDOUT:
> 
> ```
> ERROR:root:Cleanup svg failed
> Traceback (most recent call last):
>   File "/Users/bchristel/khan/graphie-to-png/cleanup_svg.py", line 171, in cleanup_svg
>     return _run_svgo(new_svgdata.decode('utf-8'))
>   File "/Users/bchristel/khan/graphie-to-png/cleanup_svg.py", line 44, in _run_svgo
>     encoding='utf-8')
> TypeError: __init__() got an unexpected keyword argument 'encoding'
> ```

Most likely is that the `gunicorn` on your path is a python2 gunicorn.  You'll have to remove that first, or set things up so the python3 gunicorn is earlier on your path.